# Generated by Django 5.2.6 on 2025-09-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_candidateprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='headline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='links',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='work_experience',
            field=models.TextField(blank=True),
        ),
    ]
