# Generated by Django 5.2.6 on 2025-10-25 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_conversation_message'),
        ('home', '0005_profile_commute_radius_miles'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this saved search', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('headline_keywords', models.CharField(blank=True, help_text='Keywords to search in headlines', max_length=500)),
                ('education_keywords', models.CharField(blank=True, help_text='Keywords to search in education', max_length=500)),
                ('experience_keywords', models.CharField(blank=True, help_text='Keywords to search in work experience', max_length=500)),
                ('notify_on_new_matches', models.BooleanField(default=True, help_text='Get notified when new candidates match this search')),
                ('last_notified_at', models.DateTimeField(blank=True, help_text='Last time notifications were sent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this search is active')),
                ('recruiter', models.ForeignKey(limit_choices_to={'role': 'recruiter'}, on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(blank=True, related_name='saved_searches', to='home.skill')),
            ],
            options={
                'verbose_name': 'Saved Search',
                'verbose_name_plural': 'Saved Searches',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('saved_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.savedsearch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
