# Generated by Django 5.2.6 on 2025-10-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_application_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_visible',
            field=models.BooleanField(default=True, help_text='Make profile visible to recruiters in search'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_education',
            field=models.BooleanField(default=True, help_text='Show education to recruiters'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_headline',
            field=models.BooleanField(default=True, help_text='Show headline to recruiters'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_links',
            field=models.BooleanField(default=True, help_text='Show links to recruiters'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_location',
            field=models.BooleanField(default=True, help_text='Show location to recruiters'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_skills',
            field=models.BooleanField(default=True, help_text='Show skills to recruiters'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_work_experience',
            field=models.BooleanField(default=True, help_text='Show work experience to recruiters'),
        ),
    ]
