# Generated by Django 5.2.6 on 2025-10-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profile_profile_visible_profile_show_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('review', 'Under Review'), ('interview', 'Interview'), ('offer', 'Offer'), ('closed', 'Closed')], default='applied', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
