# Generated by Django 5.2.6 on 2025-10-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_application_status_application_status_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='commute_radius_miles',
            field=models.PositiveIntegerField(default=25, help_text='Preferred commute radius in miles (0 = no limit, remote only)'),
        ),
    ]
