# Generated by Django 5.2.6 on 2025-10-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_profile_commute_radius_miles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(blank=True, help_text="User's latitude for location-based job matching", null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.FloatField(blank=True, help_text="User's longitude for location-based job matching", null=True),
        ),
    ]
