# Generated by Django 5.2.6 on 2025-10-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_add_user_location_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='commute_radius_miles',
            field=models.PositiveIntegerField(default=0, help_text='Preferred commute radius in miles (0 = no limit)'),
        ),
    ]
